services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - user-service-network

  user-service:
    build: .
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://root:password@mongodb:27017/user-service?authSource=admin
    networks:
      - user-service-network

  user-admin:
    build: ./frontend
    container_name: user-admin
    ports:
      - "8501:8501"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://root:password@mongodb:27017/?authSource=admin
      - DB_NAME=user-service
    networks:
      - user-service-network

networks:
  user-service-network:
    driver: bridge

volumes:
  mongodb_data:
