spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:password@localhost:27017/user-service?authSource=admin}
  application:
    name: user-service

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    com.example.userservice: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 